task_management/urls.py
# from django.contrib import admin
# from django.urls import path,include
# from debug_toolbar.toolbar import debug_toolbar_urls

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("tasks/",include("tasks.urls"))
# ]+debug_toolbar_urls()

from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),  # ✅ root path এ tasks app কে include করো
] + debug_toolbar_urls()

tasks/urls.py
# from django.urls import path
# from tasks.views import manager_dashboard, user_dashboard, test,create_task,view_task,update_task,delete_task

# urlpatterns = [
#     path('manager_dashboard/',manager_dashboard,name='manager_dashboard'),
#     path('user_dashboard/',user_dashboard),
#     path('test/', test),
#     path('create-task/',create_task,name="create_task"),
#     path('view_task/',view_task),
#     path('update_task/<int:id>/',update_task,name="update_task"),
#     path('delete_task/<int:id>/',delete_task,name="delete_task"),
# ]

from django.urls import path 
from tasks.views import manager_dashboard, user_dashboard, test, create_task, view_task, update_task, delete_task

urlpatterns = [
    path('', manager_dashboard, name='home'),  # ✅ Root path এর জন্য view
    path('manager_dashboard/', manager_dashboard, name='manager_dashboard'),
    path('user_dashboard/', user_dashboard),
    path('test/', test),
    path('create-task/', create_task, name="create_task"),
    path('view_task/', view_task),
    path('update_task/<int:id>/', update_task, name="update_task"),
    path('delete_task/<int:id>/', delete_task, name="delete_task"),
]

tasks/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed')
    ]

    project = models.ForeignKey("Project",
    on_delete=models.CASCADE,
    default=1
    )
    assigned_to = models.ManyToManyField(Employee,related_name="tasks")
    title = models.CharField(max_length=255, null=True, default=" ")
    description = models.TextField()
    due_date = models.DateField()
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='PENDING')
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class TaskDetail(models.Model):
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    PRIORITY_OPTIONS = (
        (HIGH,'High'),
        (MEDIUM,'Medium'),
        (LOW, 'Low')
    )
    task = models.OneToOneField(Task,
            on_delete=models.CASCADE,
            related_name="details"
            )
    # assigned_to = models.CharField(max_length=120)
    priority = models.CharField(
        max_length=1,choices=PRIORITY_OPTIONS,default=LOW)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Details form Task {self.task.title}"


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(blank=True,null=True)
    start_date = models.DateField()

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task, TaskDetail

# Django Form
class TaskForm(forms.Form):
    title = forms.CharField(max_length=250,label="Task Title")
    # description = forms.CharField(widget=forms.Textarea)
    description = forms.CharField(widget=forms.Textarea, label="Task Description")
    due_date = forms.DateField(widget=forms.SelectDateWidget,label="Due Date")
    assigned_to = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=[], label='Assigned To')

    def __init__(self,*args,**kwargs):
        # print(args,kwargs)
        employees = kwargs.pop('employees', [])
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].choices = [
            (emp.id, emp.name) for emp in employees]

class StyledFormMixin:

    """Mixin to apply style to form field"""
    default_classes = "border-2 border-gray-300 p-2 mb-2 w-full rounded-lg shadow-sm focus:outline-none focus:border-rose-500 focus:ring-rose-500"

    def apply_styled_widgets(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}",
                    'rows': 5

                })
            elif isinstance(field.widget,forms.SelectDateWidget):
                field.widget.attrs.update({
                    'class': "border-2 border-gray-300 w-full p-3 rounded-lg shadow-sm focus:outline-none focus:border-rose-500 focus:ring-rose-500"
                })
            elif isinstance(field.widget,forms.CheckboxSelectMultiple):
                field.widget.attrs.update({
                    'class': "space-y-2"
                })
            else:
                field.widget.attrs.update({
                    'class': self.default_classes
                })

#Django Model Form

class TaskModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Task 
        fields = ['title', 'description','due_date','assigned_to']

        widgets = {
            'due_date': forms.SelectDateWidget,
            'assigned_to': forms.CheckboxSelectMultiple
        }


    """widget using """
    def __init__(self,*arg,**kwarg):
        super().__init__(*arg,**kwarg)
        self.apply_styled_widgets()

class TaskDetailModelForm(StyledFormMixin,forms.ModelForm):
    class Meta:
        model = TaskDetail 
        fields = ['priority','notes']


    def __init__(self, *arg, **kwarg):
        super().__init__(*arg, **kwarg)
        self.apply_styled_widgets()

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.forms import TaskForm, TaskModelForm,TaskDetailModelForm
from tasks.models import Employee, Task, TaskDetail, Project
from datetime import date
from django.db.models import Q, Count, Max, Avg, Min
from django.contrib import messages

# Create your views he

def manager_dashboard(request):
    
    
    # total_task = tasks.count()
    # completed_task = Task.objects.filter(status="COMPLETED").count()
    # in_progress_task = Task.objects.filter(status="IN_PROGRESS").count()
    # pending_task = Task.objects.filter(status="PENDING").count()

    # context = {
    #     "tasks": tasks,
    #     "total_task": total_task,
    #     "pending_task": pending_task,
    #     "in_progress_task": in_progress_task,
    #     "completed_task": completed_task
    # }

    type = request.GET.get('type','all')

    counts = Task.objects.aggregate(
        total = Count('id'),
        completed = Count('id',filter=Q(status='COMPLETED')),
        in_progress = Count('id',filter=Q(status='IN_PROGRESS')),
        pending = Count('id',filter=Q(status='PENDING')),
    )

    #Retriving task date

    base_query = Task.objects.select_related("details").prefetch_related("assigned_to")

    if type == 'completed':
            tasks = base_query.filter(status="COMPLETED")
    elif type == 'in_progress':
            tasks = base_query.filter(status="IN_PROGRESS")
    elif type == 'pending':
            tasks = base_query.filter(status="PENDING")
    elif type == 'all':
            tasks = base_query.all()

    context ={
        "tasks": tasks,
        "counts": counts

    }

    return render(request, "dashboard/manager_dashboard.html",context)

def user_dashboard(request):
    return render(request, 'dashboard/user_dashboard.html')
def test(request):
    context = {
        'names': ['Mahfuj','Karim','Habib','John'],
        'age': 27
    }
    return render(request, 'test.html',context)

def create_task(request):
    # employees = Employee.objects.all()

    task_form = TaskModelForm()
    task_detail_form = TaskDetailModelForm()

    if request.method == "POST":
        task_form = TaskModelForm(request.POST)
        task_detail_form = TaskDetailModelForm(request.POST)
        if task_form.is_valid() and task_detail_form:
            """For Model Form Data"""
            # print(form)
            task=task_form.save()
            task_detail=task_detail_form.save(commit=False)
            task_detail.task=task
            task_detail.save()

            messages.success(request,"Task Created Successfully")

            return redirect("create_task")
            """For Django Form Data"""

    context = {"task_form": task_form,"task_detail_form":task_detail_form}
    return render(request, "task_form.html",context)


def view_task(request):

    # tasks = TaskDetail.objects.select_related("task").all()
    tasks = Task.objects.select_related("project").all()
    # tasks = Project.objects.all()

    # tasks = Task.objects.prefetch_related("assigned_to").all()
    # task_count = Task.objects.aggregate(num_task=Count('id'))
    # projects = Project.objects.annotate(num_task=Count('task')).order_by("num_task")
    return render(request,"dashboard/show_task.html",{"tasks": tasks})



def update_task(request,id):
    task = Task.objects.get(id=id)
    task_form = TaskModelForm(instance=task)

    if task.details:
        task_detail_form = TaskDetailModelForm(instance=task.details)

    if request.method == "POST":
        task_form = TaskModelForm(request.POST,instance=task)
        task_detail_form = TaskDetailModelForm(request.POST,instance=task.details)
        if task_form.is_valid() and task_detail_form:
            """For Model Form Data"""
            # print(form)
            task=task_form.save()
            task_detail=task_detail_form.save(commit=False)
            task_detail.task=task
            task_detail.save()

            messages.success(request,"Task Updated Successfully")

            return redirect("update_task",id)
            """For Django Form Data"""

    context = {"task_form": task_form,"task_detail_form":task_detail_form}
    return render(request, "task_form.html",context)

def delete_task(request,id):
     if request.method == 'POST':
          task = Task.objects.get(id=id)
          task.delete()

          messages.success(request, "Task Delete Successfully")
          return redirect('manager_dashboard')
     else:
          messages.success(request, "Something went worng")
          return redirect('manager_dashboard')

tasks/templates/dashboard/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- ✅ Tailwind CDN Link -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+JP&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/output.css' %}" />
    <style>
      body {
        font-family: "inter", sans-serif;
      }
    </style>
  </head>

  <body class="bg-gray-100 p-6">
    <div class="mx-w-[1400px] mx-auto">
      {% comment %} header {% endcomment %}
      <header class="flex justify-between items-center mb-8">
        <h1 class="text-2xl font-bold">Dashboard</h1>
        <div class="flex items-center gap-4">
          <button class="p-2 rounded-full hover:bg-gray-300 relative">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-6"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0"
              />
            </svg>
          </button>
          <button
            class="w-10 h-10 bg-blue-500 rounded-full text-white font-bold items-center justify-center"
          >
            B
          </button>
        </div>
      </header>
      <main>
        {% comment %} Stats Grid {% endcomment %}
        <div class="grid grid-cols-4 gap-6 mb-8">

          <a href="{% url 'manager_dashboard' %}">
            <div class="bg-white rounded-xl p-6 shadow-sm">
              <h3 class="text-sm font-medium text-gray-500 mb-3">TOTAL TASK</h3>
              <div class="flex justify-between items-start">
                <div>
                  <p class="text-3xl font-semibold mb-2">{{counts.total}}</p>
                  <p class="text-gray-500 text-sm">11 last month</p>
                </div>
                <div class="bg-green-100 rounded-full p-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    class="w-6 h-6 text-blue-600"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </a>

          <a href="{% url 'manager_dashboard' %}?type=completed">
            <div class="bg-white rounded-xl p-6 shadow-sm">
              <h3 class="text-sm font-medium text-gray-500 mb-3">
                COMPLETED TASK
              </h3>
              <div class="flex justify-between items-start">
                <div>
                  <p class="text-3xl font-semibold mb-2">
                    {{counts.completed}}
                  </p>
                  <p class="text-gray-500 text-sm">11 last month</p>
                </div>
                <div class="bg-green-100 rounded-full p-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    class="w-6 h-6 text-blue-600"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </a>

          <a href="{% url 'manager_dashboard' %}?type=in_progress">
            <div class="bg-white rounded-xl p-6 shadow-sm">
              <h3 class="text-sm font-medium text-gray-500 mb-3">
                TASK IN PROGRESS
              </h3>
              <div class="flex justify-between items-start">
                <div>
                  <p class="text-3xl font-semibold mb-2">
                    {{counts.in_progress}}
                  </p>
                  <p class="text-gray-500 text-sm">11 last month</p>
                </div>
                <div class="bg-yellow-100 rounded-full p-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    class="w-6 h-6 text-blue-600"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </a>

          <a href="{% url 'manager_dashboard' %}?type=pending">
            <div class="bg-white rounded-xl p-6 shadow-sm">
              <h3 class="text-sm font-medium text-gray-500 mb-3">TODOS</h3>
              <div class="flex justify-between items-start">
                <div>
                  <p class="text-3xl font-semibold mb-2">{{counts.pending}}</p>
                  <p class="text-gray-500 text-sm">11 last month</p>
                </div>
                <div class="bg-purple-100 rounded-full p-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    class="w-6 h-6 text-purple-600"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </a>
        </div>
        <div
        {% if messages %}
          {% for message in messages %}
        class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500 {% endif %}">
        {{message}}
          {% endfor %}
        {% endif %}
      </div>
        {% comment %} Task Table {% endcomment %} 
         {% block Tasks %} 
         {% endblock Tasks %}
      </main>
    </div>
  </body>
</html>

tasks/templates/dashboard/manager_dashboard.html
{% extends "dashboard/dashboard.html" %} 

{% block title %}Manager Dashboard{% endblock title %}

{% block Tasks %}

<div class="bg-white rounded-xl shadow-sm">
  <div
    class="grid grid-cols-4 p-4 border-b border-gray-100 text-gray-500 text-sm"
  >
    <div>TASK TITLE</div>
    <div>PRIORITY</div>
    <div>TEAM</div>
    <div>CREATED AT</div>
  </div>
  <div>
    {% for task in tasks %}
          {% comment %} TASK ITEMS-1 {% endcomment %}
    <div class="grid grid-cols-4 p-4 items-center">
      <div class="flex items-center gap-2">
        <div class="w-2 h-2 bg-green-500 rounded-full"></div>
        <div>
          <span>{{task.title}}</span>
          <a href="{% url "update_task" task.id%}" class="px-3 py-2 bg-green-500"> Edit </a>
          <form action="{% url "delete_task" task.id%}" method='POST'>
            {% csrf_token %}
            <button type="submit" class="px-3 py-2 bg-red-600" > Delete </button>
          </form>
        </div>
      </div>
      <div>
        <span class="bx-3 py-1 rounded-full bg-blue-50 text-blue-600 text-sm"
          >{{task.details.get_priority_display}}</span
        >
      </div>
      <div>
        <div class="flex -space-x-2">
          {% for emp in task.assigned_to.all %}
            <div class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white">
            {{emp.name|slice:':1'}}
          </div>
          {% endfor %}
          {% comment %} <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            JS
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            B
          </div> {% endcomment %}
        </div>
      </div>
      <div>
        <span class="text-gray-500">{{task.created_at|timesince}}</span>
      </div>
    </div>
    {% endfor %}
    {% comment %} TASK ITEMS-2 {% endcomment %}
    {% comment %} <div class="grid grid-cols-4 p-4 items-center">
      <div class="flex items-center gap-2">
        <div class="w-2 h-2 bg-yellow-500 rounded-full"></div>
        <div>
          <span>Test Task</span>
        </div>
      </div>
      <div>
        <span class="bx-3 py-1 rounded-full bg-gray-50 text-gray-600 text-sm"
          >Normal</span
        >
      </div>
      <div>
        <div class="flex -space-x-2">
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            AJ
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            EV
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            B
          </div>
        </div>
      </div>
      <div>
        <span class="text-gray-500">9 months ago</span>
      </div>
    </div> {% endcomment %}
    {% comment %} TASK ITEMS-3 {% endcomment %}
    {% comment %} <div class="grid grid-cols-4 p-4 items-center">
      <div class="flex items-center gap-2">
        <div class="w-2 h-2 bg-red-500 rounded-full"></div>
        <div>
          <span>Test Task</span>
        </div>
      </div>
      <div>
        <span class="bx-3 py-1 rounded-full bg-gray-50 text-red-600 text-sm"
          >High</span
        >
      </div>
      <div>
        <div class="flex -space-x-2">
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            CA
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            JS
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            AJ
          </div>
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm border-2 border-white"
          >
            B
          </div>
        </div>
      </div>
      <div>
        <span class="text-gray-500">10 months ago</span>
      </div>
    </div> {% endcomment %}
  </div>
</div>

{% endblock Tasks %}

tasks/templates/dashboard/show_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
     <div>
        <ol>
            <li> 
                {% for task in tasks%}
                    <p>{{task.title}}</p>
                    <p>{{task.id}}</p>
                {% endfor %}
            </li>
        </ol>
        {% comment %} <p>{{task_count}}</p> {% endcomment %}
    </div>
    
</body>
</html>

tasks/templates/dashboard/user_dashboard.html
{% extends "dashboard/dashboard.html" %}

{% block title %} User Dashboard {% endblock title %}

{% block Tasks %}

<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
  <!-- Today's Task -->
  <div class="bg-white rounded-xl p-6 shadow-sm h-full">
    <h1 class="text-xl font-bold text-black mb-3">Today's Task</h1>
    <div class="flex justify-between items-start">
      <!-- Dots + Tasks -->
      <div class="flex gap-2">
        <div class="flex flex-col gap-6 mt-2">
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
          <div class="w-2 h-2 bg-yellow-500 rounded-full"></div>
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
        </div>
        <div class="flex flex-col">
          <div class="mb-2">Complete Project Proposal</div>
          <div class="mb-2">Review team updates</div>
          <div class="mb-2">Prepare for client meeting</div>
        </div>
      </div>
      <!-- Priority -->
      <div class="flex flex-col text-right">
        <div class="text-sm text-gray-500 mb-3">High</div>
        <div class="text-sm text-gray-500 mb-3">Normal</div>
        <div class="text-sm text-gray-500 mb-2">Low</div>
      </div>
    </div>
  </div>
  <!-- All Tasks -->
  <div class="bg-white rounded-xl p-6 shadow-sm h-full">
    <h1 class="text-xl font-bold text-black mb-4">All Tasks</h1>
    <div
      class="grid grid-cols-4 p-2 border-b border-gray-100 text-gray-500 text-sm font-medium"
    >
      <div>TASK TITLE</div>
      <div>PRIORITY</div>
      <div>TEAM</div>
      <div>CREATED AT</div>
    </div>
    {% comment %} <!-- TASK ROWS --> {% endcomment %}
    <div class="space-y-2">
      {% comment %} <!-- Task Row 1 --> {% endcomment %}
      <div class="grid grid-cols-4 items-center text-sm">
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-green-500 rounded-full"></div>
          <span>Test Low Task</span>
        </div>
        <div><span class="px-2 py-1 bg-blue-50 text-blue-600">Low</span></div>
        <div class="flex -space-x-2">
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            CA
          </div>
          <div
            class="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            JS
          </div>
          <div
            class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            B
          </div>
        </div>
        <div class="text-gray-500">9 months ago</div>
      </div>

      {% comment %} <!-- Task Row 2 --> {% endcomment %}
      <div class="grid grid-cols-4 items-center text-sm">
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-yellow-500 rounded-full"></div>
          <span>Test Task</span>
        </div>
        <div>
          <span class="px-2 py-1 bg-gray-50 text-black-600">Normal</span>
        </div>
        <div class="flex -space-x-2">
          <div
            class="w-8 h-8 rounded-full bg-red-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            AJ
          </div>
          <div
            class="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            EV
          </div>
          <div
            class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            B
          </div>
        </div>
        <div class="text-gray-500">9 months ago</div>
      </div>

      {% comment %} <!-- Task Row 3 --> {% endcomment %}
      <div class="grid grid-cols-4 items-center text-sm">
        <div class="flex items-center gap-2">
          <div class="w-2 h-2 bg-red-500 rounded-full"></div>
          <span>Test Task</span>
        </div>
        <div><span class="px-2 py-1 bg-red-50 text-red-600">High</span></div>
        <div class="flex -space-x-2">
          <div
            class="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            CA
          </div>
          <div
            class="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            JS
          </div>
          <div
            class="w-8 h-8 rounded-full bg-red-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            AJ
          </div>
          <div
            class="w-8 h-8 rounded-full bg-yellow-500 flex items-center justify-center text-white text-xs border-2 border-white"
          >
            B
          </div>
        </div>
        <div class="text-gray-500">10 months ago</div>
      </div>
    </div>
  </div>
</div>
{% endblock Tasks %}